apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: guestbook
images:
- name: ghcr.io/dhpup/guestbook
  newName: ghcr.io/dhpup/guestbook
  newTag: 0.1.39
